//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItPage.UnitConverterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnitConverterService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InchestoCentimeter", ReplyAction="http://tempuri.org/IService1/InchestoCentimeterResponse")]
        string InchestoCentimeter(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InchestoCentimeter", ReplyAction="http://tempuri.org/IService1/InchestoCentimeterResponse")]
        System.Threading.Tasks.Task<string> InchestoCentimeterAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PoundtoKilogram", ReplyAction="http://tempuri.org/IService1/PoundtoKilogramResponse")]
        string PoundtoKilogram(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PoundtoKilogram", ReplyAction="http://tempuri.org/IService1/PoundtoKilogramResponse")]
        System.Threading.Tasks.Task<string> PoundtoKilogramAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItPage.UnitConverterService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItPage.UnitConverterService.IService1>, TryItPage.UnitConverterService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InchestoCentimeter(string str) {
            return base.Channel.InchestoCentimeter(str);
        }
        
        public System.Threading.Tasks.Task<string> InchestoCentimeterAsync(string str) {
            return base.Channel.InchestoCentimeterAsync(str);
        }
        
        public string PoundtoKilogram(string str) {
            return base.Channel.PoundtoKilogram(str);
        }
        
        public System.Threading.Tasks.Task<string> PoundtoKilogramAsync(string str) {
            return base.Channel.PoundtoKilogramAsync(str);
        }
    }
}
